FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04

# ** [Optional] Uncomment this section to install additional packages. **
RUN userdel vscode
RUN curl -s "https://raw.githubusercontent.com/Gantner-Electronics/coding-guidelines/main/frontend/.devcontainer/setup.sh" | sh
