# ubuntu is required to install/use cypress in the container
FROM mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04

# ** [Optional] Uncomment this section to install additional packages. **
RUN curl -s "" | sh